# Generated by Django 5.2.3 on 2025-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
