# Generated by Django 5.2.3 on 2025-07-11 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_plato_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingrediente',
        ),
    ]
