# Generated by Django 5.2.3 on 2025-07-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_delete_ingrediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
