# Generated by Django 5.2.3 on 2025-07-11 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_pedido_turno_alter_pedido_cajero_alter_pedido_mesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
    ]
