# Generated by Django 5.2.3 on 2025-07-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_pedido_turno_alter_pedidoplato_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoplato',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoplato',
            name='plato',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoPlato',
        ),
    ]
