# Generated by Django 5.2.3 on 2025-07-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nota_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
