# Generated by Django 5.2.3 on 2025-07-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_pedido_fecha_actualizacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('preparado', 'Preparado')], default='pendiente', max_length=20),
        ),
    ]
